#Local Server
datasrc.username=MUBIPS
datasrc.password=mubips
datasrc.url=jdbc:oracle:thin:@122.165.217.18:1521/BIPSFIJI

#UAT Server
#datasrc.url=jdbc:oracle:thin:@172.17.242.73:1535/BIPAY
#datasrc.username=BIPAY
#datasrc.password=Bank_1234

#Production Server
#datasrc.url=jdbc:oracle:thin:@172.17.42.219:1535/BIPAY
#datasrc.username=BIPAY
#datasrc.password=Bank_1234

#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=IST

output.exportpath=D://BIPS/doc/

#bank address
default.bank_address= PLOT NO. 1108, AKD HOUSE, QUEENS ROAD, MAIN MALL, GABORONE, BOTSWANA

#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.servlet.context-path=/Bipsportal
server.port=8001
spring.jpa.hibernate.ddl-auto=validate

# Increase the maximum file size to 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

userpassword=Bobbotswana@1234
ipsx.qr.payeecode=BARBBWGUXXXX
ipsx.qr.globalUnique=me.bornfire
ipsx.qr.payload=01
ipsx.qr.poiMethod_static=11
ipsx.qr.poiMethod_dynamic=12
ipsx.remitterbank=BOB
ipsx.initiatorbank=BOB

bob.cutofftime=23:50
#BOB Agent Details
ipsx.user=BARB0AMBOXXANRT
ipsx.sender=BARB0AMBOXXANRT
ipsx.qrPartiipant=BARBBWGUXXXX
ipsx.bicfi=BARBBWGUXXXX
ipsx.dbtragt=BARBBWGUXXXX
ipsx.dbtragtacct=BARBBWGUXXXX
ipsx.msgReceiver=BOMMMUPLXIPS
#ipsx.msgReceiverbicfi=TSTBMUMU
ipsx.msgReceiverbicfi=BOMMMUPL
ipsx.userS=BARB


#CIM CBS INPUT
cimCBS.channelID=MOBILE
cimCBS.servicereqversion=1.0
cimCBS.servicereqID=POSTPAYMENTNEW
cimCBS.countryCode=BW
cimCBS.servicereqversionrev=2.0

##must be true or false
ipsx.crccheck=true
ipsx.upiQRcheck=false


#ESB Channel
cimCBS.incCRChannel=BOM
cimCBS.rtpCRChannel=MOFINANS
cimCBS.outDBChannel=BIPS

bob.crncycode=BWP
bob.bankcode=012

#UAT Server
connect24.url=https://BIPSBTWTDDB301.bankofbaroda.co.in:8443/IPSConnect24
#connect24.url=http://172.17.242.73:8443/IPSConnect24

#Production Server
#connect24.url=http://172.16.52.20:26036/IPSConnect24

bob.SchmType=SBA
trchtype.tran=T

#SMS UAT
sms.IPaddress=172.16.251.105
sms.SMSport=9002
sms.dcode=3130
sms.subuid=BOTQRSMS
sms.pwd=SGteaaFIHx
sms.sender=BOBTXN
sms.intflag=1
sms.msgtype=S
sms.alert=0

#OTP UAT
otp.IPaddress=172.16.251.105
otp.OTPport=9002
otp.dcode=3130
otp.subuid=BOTQROTP
otp.pwd=qwIekmOJuH1FFd
otp.sender=BOBOTP
otp.intflag=1
otp.msgtype=S
otp.alert=1

internaldeviceid=priyu

ips.feesaccount=95212342701006


